### ISSUE TITLE
Is it possible to support gzip content?

### ISSUE THREAD

**Issue by dlintw** [jwilner/rte#26]
I want to use RTE with mithril.js as frontend.  The original mithril.js uncompressed is about 24K bytes. The compressed size is about 8K.
Could you provide an example to handle:
1. if browser client accept gzip content, then send compressed version of mithril.js.
2. if not  accept gzip content, then send un-compressed version of mithril.js.

**Comment by jwilner** [comment]
Sure, @dlintw. RTE doesn't aim to support this kind of stuff out of the box, but it's easy to add in. A popular middleware that does just what you want is: https://github.com/nytimes/gziphandler

You might use it like:
```go
mux := rte.Must(rte.Routes("GET /mithril.js", gziphandler.GzipHandler(myHandler)))
```

As the linked to repo mentions though, this is often handled best by a reverse-proxy if you have one -- e.g. nginx, https://docs.nginx.com/nginx/admin-guide/web-server/compression/
